command: ["streamlit", "run", "app.py", "--server.port", "8000"]

env:
  # MLflow tracking
  - name: MLFLOW_TRACKING_URI
    value: "databricks"

  # App resources (from databricks.yml)
  - name: VOLUME_PATH
    valueFrom: 'source-volume'
  - name: SQL_WAREHOUSE_ID
    valueFrom: 'parse-warehouse'
  - name: AI_QUERY_ENDPOINT
    valueFrom: 'ai-query-endpoint'
  - name: LOGS_VOLUME_PATH
    valueFrom: 'logs-volume'
